[0m12:35:52.772852 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022BB6AB33E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022BB7263F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022BB6AB00B0>]}


============================== 12:35:52.783219 | 29e06ce1-a533-4a44-a377-9da0975699b1 ==============================
[0m12:35:52.783219 [info ] [MainThread]: Running with dbt=1.8.7
[0m12:35:52.783219 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\matsy\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m12:37:04.463331 [debug] [MainThread]: Starter project path: C:\Users\matsy\dbt_workspace\dbt-coreProj\Lib\site-packages\dbt\include\starter_project
[0m12:37:04.510493 [info ] [MainThread]: 
Your new dbt project "MyProjtest" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:37:04.510493 [info ] [MainThread]: Setting up your profile.
[0m12:38:25.992713 [info ] [MainThread]: Profile MyProjtest written to C:\Users\matsy\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:38:25.992713 [debug] [MainThread]: Command `dbt init` succeeded at 12:38:25.992713 after 153.33 seconds
[0m12:38:25.992713 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022BB6852180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022BB70ADB20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022BB69229F0>]}
[0m12:38:25.992713 [debug] [MainThread]: Flushing usage events
[0m12:42:05.034393 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B091AAFAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B0913514C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B091352C90>]}


============================== 12:42:05.034393 | a224527e-aeb2-43d1-b01c-a27bf7cde9d4 ==============================
[0m12:42:05.034393 [info ] [MainThread]: Running with dbt=1.8.7
[0m12:42:05.034393 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\matsy\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:42:05.034393 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\matsy\dbt_workspace\dbt-coreProj\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:42:05.040471 [debug] [MainThread]: Command `dbt run` failed at 12:42:05.040471 after 0.12 seconds
[0m12:42:05.040471 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B091AAFAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B091B603E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B091B60C20>]}
[0m12:42:05.040471 [debug] [MainThread]: Flushing usage events
[0m12:43:31.575350 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C21A40E60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C21A40C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C21273950>]}


============================== 12:43:31.575350 | 0a377d34-37f7-48c1-8d07-204d6445a9a7 ==============================
[0m12:43:31.575350 [info ] [MainThread]: Running with dbt=1.8.7
[0m12:43:31.575350 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\matsy\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'C:\\Users\\matsy\\dbt_workspace\\dbt-coreProj\\logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:43:32.570715 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '0a377d34-37f7-48c1-8d07-204d6445a9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C3C5C7F20>]}
[0m12:43:32.608667 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '0a377d34-37f7-48c1-8d07-204d6445a9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C20C235C0>]}
[0m12:43:32.608667 [info ] [MainThread]: Registered adapter: bigquery=1.8.3
[0m12:43:32.617263 [debug] [MainThread]: checksum: 4af21dafb485259c48497ac86b711ddb1982f3d0f1c0ca4e09356de488b753c0, vars: {}, profile: , target: , version: 1.8.7
[0m12:43:32.617263 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m12:43:32.617263 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '0a377d34-37f7-48c1-8d07-204d6445a9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C3ADDBC50>]}
[0m12:43:33.929515 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.MyProjtest.example
[0m12:43:33.931774 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '0a377d34-37f7-48c1-8d07-204d6445a9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C3C88E7E0>]}
[0m12:43:34.051447 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '0a377d34-37f7-48c1-8d07-204d6445a9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C3C9E6C90>]}
[0m12:43:34.054567 [info ] [MainThread]: Found 479 macros
[0m12:43:34.054567 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '0a377d34-37f7-48c1-8d07-204d6445a9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C3C9CBB60>]}
[0m12:43:34.054567 [info ] [MainThread]: 
[0m12:43:34.054567 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m12:43:34.054567 [debug] [MainThread]: Command end result
[0m12:43:34.075801 [debug] [MainThread]: Command `dbt run` succeeded at 12:43:34.075801 after 2.59 seconds
[0m12:43:34.076684 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C1E012D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C217B46E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C3B0DFDA0>]}
[0m12:43:34.076684 [debug] [MainThread]: Flushing usage events
[0m12:56:29.809622 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001968D0193D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001968D6F3DA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001968D6F15E0>]}


============================== 12:56:29.813736 | b930ab12-71d4-449a-ad2d-40460c9b90db ==============================
[0m12:56:29.813736 [info ] [MainThread]: Running with dbt=1.8.7
[0m12:56:29.813736 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\matsy\\.dbt', 'log_path': 'C:\\Users\\matsy\\dbt_workspace\\dbt-coreProj\\logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:56:29.830573 [info ] [MainThread]: Setting up your profile.
[0m13:02:39.863514 [info ] [MainThread]: Profile MyProjtest written to C:\Users\matsy\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:02:39.863514 [debug] [MainThread]: Command `dbt init` succeeded at 13:02:39.863514 after 370.20 seconds
[0m13:02:39.868570 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196A85DCF20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196A860A180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001968E0761B0>]}
[0m13:02:39.869583 [debug] [MainThread]: Flushing usage events
[0m13:07:44.976701 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EB32C300B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EB32C30C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EB333A0AD0>]}


============================== 13:07:44.980733 | 153b7da7-7e2c-488c-a8bc-967287ba2f47 ==============================
[0m13:07:44.980733 [info ] [MainThread]: Running with dbt=1.8.7
[0m13:07:44.980733 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\matsy\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:07:44.996899 [info ] [MainThread]: dbt version: 1.8.7
[0m13:07:44.996899 [info ] [MainThread]: python version: 3.12.6
[0m13:07:44.997901 [info ] [MainThread]: python path: C:\Users\matsy\dbt_workspace\dbt-coreProj\Scripts\python.exe
[0m13:07:44.997901 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m13:07:45.876535 [info ] [MainThread]: Using profiles dir at C:\Users\matsy\.dbt
[0m13:07:45.876535 [info ] [MainThread]: Using profiles.yml file at C:\Users\matsy\.dbt\profiles.yml
[0m13:07:45.877932 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\matsy\dbt_workspace\dbt-coreProj\dbt_project.yml
[0m13:07:45.877932 [info ] [MainThread]: adapter type: bigquery
[0m13:07:45.878945 [info ] [MainThread]: adapter version: 1.8.3
[0m13:07:45.878945 [info ] [MainThread]: Configuration:
[0m13:07:45.878945 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m13:07:45.879947 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:07:45.879947 [info ] [MainThread]: Required dependencies:
[0m13:07:45.879947 [debug] [MainThread]: Executing "git --help"
[0m13:07:45.882943 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m13:07:45.882943 [info ] [MainThread]: Connection:
[0m13:07:45.882943 [info ] [MainThread]:   method: service-account
[0m13:07:45.882943 [info ] [MainThread]:   database: myprojtest-439206
[0m13:07:45.882943 [info ] [MainThread]:   execution_project: myprojtest-439206
[0m13:07:45.884362 [info ] [MainThread]:   schema: Test
[0m13:07:45.884362 [info ] [MainThread]:   location: US
[0m13:07:45.884362 [info ] [MainThread]:   priority: interactive
[0m13:07:45.884362 [info ] [MainThread]:   maximum_bytes_billed: None
[0m13:07:45.885375 [info ] [MainThread]:   impersonate_service_account: None
[0m13:07:45.885375 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m13:07:45.885375 [info ] [MainThread]:   job_retries: 1
[0m13:07:45.885375 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m13:07:45.886373 [info ] [MainThread]:   job_execution_timeout_seconds: 200
[0m13:07:45.886373 [info ] [MainThread]:   timeout_seconds: 200
[0m13:07:45.886373 [info ] [MainThread]:   client_id: None
[0m13:07:45.886373 [info ] [MainThread]:   token_uri: None
[0m13:07:45.887375 [info ] [MainThread]:   dataproc_region: None
[0m13:07:45.887375 [info ] [MainThread]:   dataproc_cluster_name: None
[0m13:07:45.887375 [info ] [MainThread]:   gcs_bucket: None
[0m13:07:45.887375 [info ] [MainThread]:   dataproc_batch: None
[0m13:07:45.888375 [info ] [MainThread]: Registered adapter: bigquery=1.8.3
[0m13:07:45.888375 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m13:07:45.888375 [debug] [MainThread]: Opening a new connection, currently in state init
[0m13:07:45.890373 [debug] [MainThread]: On debug: select 1 as id
[0m13:07:46.792273 [error] [MainThread]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=myprojtest-439206&j=bq:US:bfbfc792-52f5-416d-bd40-221649c25775&page=queryresults
[0m13:07:46.793575 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m13:07:46.794580 [info ] [MainThread]: [31m3 checks failed:[0m
[0m13:07:46.796580 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\matsy\dbt_workspace\dbt-coreProj\dbt_project.yml> not found

[0m13:07:46.803720 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m13:07:46.803720 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  Access Denied: Project myprojtest-439206: User does not have bigquery.jobs.create permission in project myprojtest-439206.

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m13:07:46.807005 [debug] [MainThread]: Command `dbt debug` failed at 13:07:46.807005 after 1.98 seconds
[0m13:07:46.807005 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m13:07:46.807005 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EB33185370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EB4DF074A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EB4CAC7CE0>]}
[0m13:07:46.808001 [debug] [MainThread]: Flushing usage events
[0m11:33:22.764856 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC5A840E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC5A6CF080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC599852E0>]}


============================== 11:33:22.769857 | 17165e54-68c5-4ac7-979b-c9e0c9488ed8 ==============================
[0m11:33:22.769857 [info ] [MainThread]: Running with dbt=1.8.7
[0m11:33:22.770857 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\matsy\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run --select Normal_Load', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:33:22.770857 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\matsy\dbt_workspace\dbt-coreProj\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:33:22.771858 [debug] [MainThread]: Command `dbt run` failed at 11:33:22.771858 after 0.14 seconds
[0m11:33:22.772858 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC5A648380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC5A4C9AC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC5A0D3320>]}
[0m11:33:22.772858 [debug] [MainThread]: Flushing usage events
[0m11:34:28.888604 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002007578F3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020077E0F9B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200724C6ED0>]}


============================== 11:34:28.893107 | 8822df91-e81c-43c3-96da-b42e78f3fa2e ==============================
[0m11:34:28.893107 [info ] [MainThread]: Running with dbt=1.8.7
[0m11:34:28.893107 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\matsy\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --models Normal_Load', 'send_anonymous_usage_stats': 'True'}
[0m11:34:28.894108 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\matsy\dbt_workspace\dbt-coreProj\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:34:28.895108 [debug] [MainThread]: Command `dbt run` failed at 11:34:28.895108 after 0.12 seconds
[0m11:34:28.895108 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002007825CD40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002007578F3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020077EE14C0>]}
[0m11:34:28.895108 [debug] [MainThread]: Flushing usage events
[0m11:53:23.798128 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C113DD1520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C113DD0C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C113B59A30>]}


============================== 11:53:23.801128 | ed849f7b-d9c8-4535-a85e-8e453d976e52 ==============================
[0m11:53:23.801128 [info ] [MainThread]: Running with dbt=1.8.7
[0m11:53:23.802098 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Users\\matsy\\dbt_workspace\\dbt-coreProj\\logs', 'profiles_dir': 'C:\\Users\\matsy\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --models Normal_Load', 'send_anonymous_usage_stats': 'True'}
[0m11:53:24.507761 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'ed849f7b-d9c8-4535-a85e-8e453d976e52', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C113EAD4C0>]}
[0m11:53:24.545760 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'ed849f7b-d9c8-4535-a85e-8e453d976e52', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C112C2B140>]}
[0m11:53:24.546761 [info ] [MainThread]: Registered adapter: bigquery=1.8.3
[0m11:53:24.552761 [debug] [MainThread]: checksum: 4af21dafb485259c48497ac86b711ddb1982f3d0f1c0ca4e09356de488b753c0, vars: {}, profile: , target: , version: 1.8.7
[0m11:53:24.614767 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m11:53:24.615769 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m11:53:24.615769 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.MyProjtest.example
[0m11:53:24.619767 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'ed849f7b-d9c8-4535-a85e-8e453d976e52', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C12E402660>]}
[0m11:53:24.676610 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'ed849f7b-d9c8-4535-a85e-8e453d976e52', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C12E6306B0>]}
[0m11:53:24.677610 [info ] [MainThread]: Found 479 macros
[0m11:53:24.677610 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'ed849f7b-d9c8-4535-a85e-8e453d976e52', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C12E44A450>]}
[0m11:53:24.677610 [warn ] [MainThread]: The selection criterion 'Normal_Load' does not match any enabled nodes
[0m11:53:24.679629 [info ] [MainThread]: 
[0m11:53:24.679629 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m11:53:24.681623 [debug] [MainThread]: Command end result
[0m11:53:24.703609 [debug] [MainThread]: Command `dbt run` succeeded at 11:53:24.703609 after 1.01 seconds
[0m11:53:24.704645 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C12A93C5F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C12E4DA210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C12E58D550>]}
[0m11:53:24.704645 [debug] [MainThread]: Flushing usage events
[0m13:31:05.959985 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3C1303AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3C13038F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3C1300D70>]}


============================== 13:31:05.963990 | c0c4fe2b-3793-424c-a887-17285a69eb69 ==============================
[0m13:31:05.963990 [info ] [MainThread]: Running with dbt=1.8.7
[0m13:31:05.964990 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'C:\\Users\\matsy\\dbt_workspace\\dbt-coreProj\\logs', 'profiles_dir': 'C:\\Users\\matsy\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --models Normal_Load', 'send_anonymous_usage_stats': 'True'}
[0m13:31:06.801050 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'c0c4fe2b-3793-424c-a887-17285a69eb69', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3DA34BAA0>]}
[0m13:31:06.836773 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'c0c4fe2b-3793-424c-a887-17285a69eb69', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3DA4E1100>]}
[0m13:31:06.837773 [info ] [MainThread]: Registered adapter: bigquery=1.8.3
[0m13:31:06.843768 [debug] [MainThread]: checksum: 4af21dafb485259c48497ac86b711ddb1982f3d0f1c0ca4e09356de488b753c0, vars: {}, profile: , target: , version: 1.8.7
[0m13:31:06.905254 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m13:31:06.905254 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m13:31:06.905254 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.MyProjtest.example
[0m13:31:06.909650 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'c0c4fe2b-3793-424c-a887-17285a69eb69', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3DBA63FE0>]}
[0m13:31:06.956287 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'c0c4fe2b-3793-424c-a887-17285a69eb69', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3DB9A2480>]}
[0m13:31:06.957288 [info ] [MainThread]: Found 479 macros
[0m13:31:06.957288 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'c0c4fe2b-3793-424c-a887-17285a69eb69', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3DB9EAAB0>]}
[0m13:31:06.957288 [warn ] [MainThread]: The selection criterion 'Normal_Load' does not match any enabled nodes
[0m13:31:06.958493 [info ] [MainThread]: 
[0m13:31:06.959510 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m13:31:06.960510 [debug] [MainThread]: Command end result
[0m13:31:06.981219 [debug] [MainThread]: Command `dbt run` succeeded at 13:31:06.981219 after 1.17 seconds
[0m13:31:06.982220 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3C13417C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3DB9737D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3DB9A0FE0>]}
[0m13:31:06.982220 [debug] [MainThread]: Flushing usage events
[0m15:10:20.186239 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F246556F60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2460B40B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2463DB0E0>]}


============================== 15:10:20.189571 | c43c19da-1441-4831-848e-be786cbc91ff ==============================
[0m15:10:20.189571 [info ] [MainThread]: Running with dbt=1.8.7
[0m15:10:20.190885 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\matsy\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'C:\\Users\\matsy\\dbt_workspace\\dbt-coreProj\\logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run --models Normal_Load', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:10:21.000102 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'c43c19da-1441-4831-848e-be786cbc91ff', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2448F9880>]}
[0m15:10:21.039107 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'c43c19da-1441-4831-848e-be786cbc91ff', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F25EA529C0>]}
[0m15:10:21.040106 [info ] [MainThread]: Registered adapter: bigquery=1.8.3
[0m15:10:21.046102 [debug] [MainThread]: checksum: 4af21dafb485259c48497ac86b711ddb1982f3d0f1c0ca4e09356de488b753c0, vars: {}, profile: , target: , version: 1.8.7
[0m15:10:21.112022 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m15:10:21.112950 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m15:10:21.112950 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.MyProjtest.example
[0m15:10:21.117057 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'c43c19da-1441-4831-848e-be786cbc91ff', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F25FF16480>]}
[0m15:10:21.166973 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'c43c19da-1441-4831-848e-be786cbc91ff', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2615D03E0>]}
[0m15:10:21.167981 [info ] [MainThread]: Found 479 macros
[0m15:10:21.168981 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'c43c19da-1441-4831-848e-be786cbc91ff', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2613EA450>]}
[0m15:10:21.168981 [warn ] [MainThread]: The selection criterion 'Normal_Load' does not match any enabled nodes
[0m15:10:21.169981 [info ] [MainThread]: 
[0m15:10:21.171069 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m15:10:21.172586 [debug] [MainThread]: Command end result
[0m15:10:21.194468 [debug] [MainThread]: Command `dbt run` succeeded at 15:10:21.194468 after 1.12 seconds
[0m15:10:21.194974 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F246D40590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F26120B170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F246D80D70>]}
[0m15:10:21.194974 [debug] [MainThread]: Flushing usage events
